# Form implementation generated from reading ui file 'pre_change.ui'
#
# Created by: PyQt6 UI code generator 6.8.0.dev2411221125
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import open3d as o3d
from PyQt6 import QtCore, QtGui, QtWidgets
from pyqtgraph.opengl import GLViewWidget
import numpy as np
import prechange_viewer

class pre_change_attributions():
    def __init__(self, pcd):
        self.pre_change_pcd = pcd

        self.change_matrix = np.asarray([[1, 0, 0, 0],
                                         [0, 1, 0, 0],
                                         [0, 0, 1, 0],
                                         [0, 0, 0, 1]])
